# Generated by Django 5.0.1 on 2024-02-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback_app", "0002_entity_question_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("MC", "Multiple Choice"), ("FT", "Free Text")],
                default="MC",
                max_length=2,
            ),
        ),
    ]
